// Auto-generated by: supabase gen types typescript --local
// This file will be overwritten — do not edit manually.
// Run `pnpm types` from repo root to regenerate.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      restaurants: {
        Row: {
          id: string;
          name: string;
          slug: string;
          timezone: string;
          currency: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['restaurants']['Row'], 'id' | 'created_at'> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['restaurants']['Insert']>;
      };
      restaurant_settings: {
        Row: {
          restaurant_id: string;
          receipt_header: string | null;
          receipt_footer: string | null;
          tax_rate: number;
          service_charge: number;
          allow_split_bill: boolean;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['restaurant_settings']['Row'], 'updated_at'>;
        Update: Partial<Database['public']['Tables']['restaurant_settings']['Insert']>;
      };
      staff: {
        Row: {
          id: string;
          restaurant_id: string;
          display_name: string;
          role: 'owner' | 'manager' | 'server' | 'kitchen' | 'cashier';
          pin: string | null;
          active: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['staff']['Row'], 'active' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['staff']['Insert']>;
      };
      sections: {
        Row: {
          id: string;
          restaurant_id: string;
          name: string;
          sort_order: number;
          active: boolean;
        };
        Insert: Omit<Database['public']['Tables']['sections']['Row'], 'id' | 'sort_order' | 'active'> & {
          id?: string;
        };
        Update: Partial<Database['public']['Tables']['sections']['Insert']>;
      };
      tables: {
        Row: {
          id: string;
          restaurant_id: string;
          section_id: string | null;
          name: string;
          capacity: number | null;
          status: 'available' | 'occupied' | 'reserved' | 'cleaning';
          current_order_id: string | null;
        };
        Insert: Omit<Database['public']['Tables']['tables']['Row'], 'id' | 'status'> & {
          id?: string;
          status?: 'available' | 'occupied' | 'reserved' | 'cleaning';
        };
        Update: Partial<Database['public']['Tables']['tables']['Insert']>;
      };
      menu_categories: {
        Row: {
          id: string;
          restaurant_id: string;
          name: string;
          color: string | null;
          sort_order: number;
          active: boolean;
        };
        Insert: Omit<Database['public']['Tables']['menu_categories']['Row'], 'id' | 'sort_order' | 'active'> & {
          id?: string;
        };
        Update: Partial<Database['public']['Tables']['menu_categories']['Insert']>;
      };
      menu_items: {
        Row: {
          id: string;
          restaurant_id: string;
          category_id: string;
          name: string;
          description: string | null;
          price: number;
          image_url: string | null;
          sku: string | null;
          tax_rate: number | null;
          available: boolean;
          sort_order: number;
        };
        Insert: Omit<Database['public']['Tables']['menu_items']['Row'], 'id' | 'available' | 'sort_order'> & {
          id?: string;
        };
        Update: Partial<Database['public']['Tables']['menu_items']['Insert']>;
      };
      orders: {
        Row: {
          id: string;
          restaurant_id: string;
          table_id: string | null;
          section_id: string | null;
          staff_id: string | null;
          status: 'open' | 'submitted' | 'acknowledged' | 'preparing' | 'ready' | 'served' | 'closed' | 'void';
          covers: number;
          notes: string | null;
          total: number;
          submitted_at: string | null;
          closed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['orders']['Row'], 'id' | 'status' | 'covers' | 'total' | 'created_at' | 'updated_at'> & {
          id?: string;
          status?: string;
        };
        Update: Partial<Database['public']['Tables']['orders']['Insert']>;
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          restaurant_id: string;
          menu_item_id: string;
          name: string;
          price: number;
          quantity: number;
          notes: string | null;
          status: 'pending' | 'sent' | 'acknowledged' | 'preparing' | 'ready' | 'served' | 'void';
          seat: number | null;
          sent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['order_items']['Row'], 'id' | 'quantity' | 'status' | 'created_at' | 'updated_at'> & {
          id?: string;
        };
        Update: Partial<Database['public']['Tables']['order_items']['Insert']>;
      };
      payments: {
        Row: {
          id: string;
          order_id: string;
          restaurant_id: string;
          method: 'cash' | 'card' | 'split' | 'voucher' | 'complimentary';
          amount: number;
          tip_amount: number;
          reference: string | null;
          staff_id: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['payments']['Row'], 'id' | 'tip_amount' | 'created_at'> & {
          id?: string;
        };
        Update: Partial<Database['public']['Tables']['payments']['Insert']>;
      };
      kds_stations: {
        Row: {
          id: string;
          restaurant_id: string;
          name: string;
          display_order: number;
          active: boolean;
        };
        Insert: Omit<Database['public']['Tables']['kds_stations']['Row'], 'id' | 'display_order' | 'active'> & {
          id?: string;
        };
        Update: Partial<Database['public']['Tables']['kds_stations']['Insert']>;
      };
      printers: {
        Row: {
          id: string;
          restaurant_id: string;
          name: string;
          ip_address: string;
          port: number;
          paper_width: number;
          type: 'kitchen' | 'receipt' | 'label';
          active: boolean;
        };
        Insert: Omit<Database['public']['Tables']['printers']['Row'], 'id' | 'port' | 'paper_width' | 'type' | 'active'> & {
          id?: string;
        };
        Update: Partial<Database['public']['Tables']['printers']['Insert']>;
      };
    };
  };
}

// Convenience type aliases
export type Restaurant = Database['public']['Tables']['restaurants']['Row'];
export type Staff = Database['public']['Tables']['staff']['Row'];
export type Section = Database['public']['Tables']['sections']['Row'];
export type Table = Database['public']['Tables']['tables']['Row'];
export type MenuCategory = Database['public']['Tables']['menu_categories']['Row'];
export type MenuItem = Database['public']['Tables']['menu_items']['Row'];
export type Order = Database['public']['Tables']['orders']['Row'];
export type OrderItem = Database['public']['Tables']['order_items']['Row'];
export type Payment = Database['public']['Tables']['payments']['Row'];
export type KdsStation = Database['public']['Tables']['kds_stations']['Row'];
export type Printer = Database['public']['Tables']['printers']['Row'];
